/**
 * @file useTwoFactorAuth Hook
 * @description Handles 2FA verification via SMS, email, or authenticator app
 */

import { useState, useCallback } from 'react';
import { sendEmailVerification, sendPasswordResetEmail } from 'firebase/auth';
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { auth, db } from './firebase-config';
import { usePhoneOtp } from './usePhoneOtp';
import { useTotpSetup } from './useTotpSetup';

export type TwoFactorMethod = 'sms' | 'email' | 'authenticator';

export interface TwoFactorAuthState {
  loading: boolean;
  error: string | null;
  success: boolean;
  enabled: boolean;
  method: TwoFactorMethod | null;
  codeSent: boolean;
}

export interface TwoFactorAuthResult {
  state: TwoFactorAuthState;
  enable2FA: (method: TwoFactorMethod) => Promise<boolean>;
  disable2FA: () => Promise<boolean>;
  sendVerificationCode: (method: TwoFactorMethod) => Promise<boolean>;
  verifyCode: (method: TwoFactorMethod, code: string) => Promise<boolean>;
  reset: () => void;
}

export const useTwoFactorAuth = (uid?: string): TwoFactorAuthResult => {
  const [state, setState] = useState<TwoFactorAuthState>({
    loading: false,
    error: null,
    success: false,
    enabled: false,
    method: null,
    codeSent: false,
  });

  const phoneOtp = usePhoneOtp();
  const totpSetup = useTotpSetup();

  const load2FAStatus = useCallback(async () => {
    if (!uid) return;
    try {
      const userDoc = await getDoc(doc(db, 'users', uid));
      if (userDoc.exists()) {
        const data = userDoc.data();
        setState(prev => ({
          ...prev,
          enabled: data.twoFactorEnabled || false,
          method: data.twoFactorMethod || null,
        }));
      }
    } catch (error) {
      console.error('Error loading 2FA status:', error);
    }
  }, [uid]);

  const enable2FA = useCallback(async (method: TwoFactorMethod): Promise<boolean> => {
    try {
      setState(prev => ({ ...prev, loading: true, error: null }));
      
      if (!uid) {
        throw new Error('User ID is required');
      }

      if (method === 'authenticator') {
        // Generate TOTP secret
        await totpSetup.generateSecret();
        // In production, you'd store the secret securely
      }

      // Update user document
      await updateDoc(doc(db, 'users', uid), {
        twoFactorEnabled: true,
        twoFactorMethod: method,
        updatedAt: Date.now(),
      });

      setState(prev => ({
        ...prev,
        loading: false,
        success: true,
        enabled: true,
        method,
      }));

      return true;
    } catch (error) {
      setState(prev => ({
        ...prev,
        loading: false,
        error: error instanceof Error ? error.message : 'Failed to enable 2FA',
      }));
      return false;
    }
  }, [uid, totpSetup]);

  const disable2FA = useCallback(async (): Promise<boolean> => {
    try {
      setState(prev => ({ ...prev, loading: true, error: null }));
      
      if (!uid) {
        throw new Error('User ID is required');
      }

      await updateDoc(doc(db, 'users', uid), {
        twoFactorEnabled: false,
        twoFactorMethod: null,
        updatedAt: Date.now(),
      });

      setState(prev => ({
        ...prev,
        loading: false,
        success: true,
        enabled: false,
        method: null,
      }));

      return true;
    } catch (error) {
      setState(prev => ({
        ...prev,
        loading: false,
        error: error instanceof Error ? error.message : 'Failed to disable 2FA',
      }));
      return false;
    }
  }, [uid]);

  const sendVerificationCode = useCallback(async (method: TwoFactorMethod): Promise<boolean> => {
    try {
      setState(prev => ({ ...prev, loading: true, error: null, codeSent: false }));
      
      const user = auth.currentUser;
      if (!user) {
        throw new Error('User must be authenticated');
      }

      if (method === 'sms') {
        if (!user.phoneNumber) {
          throw new Error('Phone number not linked to account');
        }
        await phoneOtp.sendOtp(user.phoneNumber);
        if (phoneOtp.state.error) {
          throw new Error(phoneOtp.state.error);
        }
      } else if (method === 'email') {
        if (!user.email) {
          throw new Error('Email not linked to account');
        }
        await sendEmailVerification(user);
      } else if (method === 'authenticator') {
        // TOTP codes are generated by the authenticator app
        // No need to send a code
        setState(prev => ({ ...prev, loading: false, codeSent: true }));
        return true;
      }

      setState(prev => ({ ...prev, loading: false, codeSent: true }));
      return true;
    } catch (error) {
      setState(prev => ({
        ...prev,
        loading: false,
        error: error instanceof Error ? error.message : 'Failed to send verification code',
      }));
      return false;
    }
  }, [phoneOtp]);

  const verifyCode = useCallback(async (
    method: TwoFactorMethod,
    code: string
  ): Promise<boolean> => {
    try {
      setState(prev => ({ ...prev, loading: true, error: null }));
      
      if (method === 'sms') {
        const result = await phoneOtp.verifyOtp(code);
        if (!result || phoneOtp.state.error) {
          throw new Error(phoneOtp.state.error || 'Invalid verification code');
        }
      } else if (method === 'email') {
        // Email verification is handled via email link
        // This would typically be handled in a separate flow
        throw new Error('Email verification requires clicking the link sent to your email');
      } else if (method === 'authenticator') {
        const isValid = await totpSetup.verifyCode(code);
        if (!isValid) {
          throw new Error('Invalid authenticator code');
        }
      }

      setState(prev => ({ ...prev, loading: false, success: true }));
      return true;
    } catch (error) {
      setState(prev => ({
        ...prev,
        loading: false,
        error: error instanceof Error ? error.message : 'Failed to verify code',
      }));
      return false;
    }
  }, [phoneOtp, totpSetup]);

  const reset = useCallback(() => {
    setState({
      loading: false,
      error: null,
      success: false,
      enabled: false,
      method: null,
      codeSent: false,
    });
  }, []);

  // Load 2FA status on mount
  React.useEffect(() => {
    if (uid) {
      load2FAStatus();
    }
  }, [uid, load2FAStatus]);

  return {
    state,
    enable2FA,
    disable2FA,
    sendVerificationCode,
    verifyCode,
    reset,
  };
};


